<a href="https://colab.research.google.com/github/SwatiKharat93/Data-Science-Practical/blob/main/PRACTICAL_NO_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Name : Swati Kashinath Kharat

Roll no : A-69

Practical No : 4

Aim : Numerical Computation with NumPy: Perform different computations using NumPy library.

1.Explain the role of NumPy in the Python scientific computing ecosystem.

NumPy plays a fundamental role in the Python scientific computing ecosystem by providing powerful tools for numerical operations and data manipulation. It introduces the concept of multidimensional arrays, which are faster and more efficient than Python lists. NumPy serves as the foundation for many other libraries used in data science, machine learning, and scientific research. It enables users to perform complex mathematical computations, handle large datasets, and implement algorithms efficiently, making it essential for scientific computing.

2.Why is NumPy considered faster than pure Python computations?

NumPy is considered faster than pure Python computations because it uses optimized C language code internally, which executes operations more efficiently. Unlike Python lists that require loops for calculations, NumPy performs operations on entire arrays at once using vectorization. This reduces the need for explicit loops and improves speed. Additionally, NumPy stores data in contiguous memory locations, which enhances performance and reduces memory usage, making it significantly faster for numerical tasks.

3.What types of mathematical operations can be performed using NumPy?

NumPy supports a wide range of mathematical operations, including basic arithmetic operations such as addition, subtraction, multiplication, and division. It also provides functions for advanced computations like mean, median, standard deviation, variance, and correlation. NumPy can perform matrix operations such as matrix multiplication, transpose, and determinant calculation. Additionally, it includes functions for trigonometry, logarithms, exponentials, and statistical analysis, making it suitable for scientific and engineering applications.

4.Explain indexing and slicing in NumPy arrays.

Indexing and slicing in NumPy arrays are used to access and manipulate specific elements or portions of the data. Indexing allows users to retrieve individual elements by specifying their position using row and column indices. Slicing enables accessing a subset of the array by specifying a range of indices. For example, users can extract specific rows, columns, or a block of data from a multidimensional array. These features make data handling flexible and efficient, especially when working with large datasets.

5.How does NumPy integrate with other libraries?
a. Pandas

NumPy integrates closely with the Pandas library, as Pandas uses NumPy arrays as its underlying data structure. DataFrames and Series in Pandas are built on NumPy, which allows fast data manipulation and numerical operations.

b. Matplotlib

NumPy works with Matplotlib to create visualizations. NumPy arrays are often used as input data for plotting graphs such as line charts, bar charts, and histograms, making data visualization easy and efficient.

c. Scikit-learn

NumPy integrates with Scikit-learn for machine learning tasks. Most algorithms in Scikit-learn require input data in the form of NumPy arrays, enabling efficient computation and model training.

In [ ]:
import numpy as np

In [ ]:
data = np.array([
    [78, 85, 90, 88, 76],
    [65, 70, 72, 68, 66],
    [90, 92, 94, 89, 91],
    [55, 60, 58, 62, 57],
    [88, 84, 86, 90, 87],
    [76, 79, 75, 80, 78],
    [92, 95, 93, 96, 94],
    [60, 65, 63, 67, 62],
    [82, 80, 85, 83, 81],
    [70, 72, 68, 74, 69]
])

In [ ]:
print("Dataset" , data)

Dataset [[78 85 90 88 76]
 [65 70 72 68 66]
 [90 92 94 89 91]
 [55 60 58 62 57]
 [88 84 86 90 87]
 [76 79 75 80 78]
 [92 95 93 96 94]
 [60 65 63 67 62]
 [82 80 85 83 81]
 [70 72 68 74 69]]

In [ ]:
sorted_data = np.sort(data)
print(sorted_data)

[[76 78 85 88 90]
 [65 66 68 70 72]
 [89 90 91 92 94]
 [55 57 58 60 62]
 [84 86 87 88 90]
 [75 76 78 79 80]
 [92 93 94 95 96]
 [60 62 63 65 67]
 [80 81 82 83 85]
 [68 69 70 72 74]]

In [ ]:
print("Total Marks:", np.sum(data))
print("Average Marks:", np.mean(data))
print("Maximum Marks:", np.max(data))
print("Minimum Marks:", np.min(data))

Total Marks: 3880
Average Marks: 77.6
Maximum Marks: 96
Minimum Marks: 55

In [ ]:
total_per_student = np.sum(data, axis=1)
print("Total per Student:", total_per_student)

Total per Student: [417 341 456 292 435 388 470 317 411 353]

In [ ]:
avg_per_subject = np.mean(data, axis=0)
print("Average per Subject:", avg_per_subject)

Average per Subject: [75.6 78.2 78.4 79.7 76.1]

In [ ]:
print("Standard Deviation:", np.std(data))

Standard Deviation: 11.718361660232201

In [ ]:
high_marks = data[data > 80]
print("Marks > 80:", high_marks)

Marks > 80: [85 90 88 90 92 94 89 91 88 84 86 90 87 92 95 93 96 94 82 85 83 81]

In [ ]:
# Add 5 grace marks
new_data = data + 5
print("After Adding Grace Marks:\n", new_data)

After Adding Grace Marks:
 [[ 83  90  95  93  81]
 [ 70  75  77  73  71]
 [ 95  97  99  94  96]
 [ 60  65  63  67  62]
 [ 93  89  91  95  92]
 [ 81  84  80  85  83]
 [ 97 100  98 101  99]
 [ 65  70  68  72  67]
 [ 87  85  90  88  86]
 [ 75  77  73  79  74]]

In [ ]:
print("Square:\n", np.square(data))
print("Square Root:\n", np.sqrt(data))

Square:
 [[6084 7225 8100 7744 5776]
 [4225 4900 5184 4624 4356]
 [8100 8464 8836 7921 8281]
 [3025 3600 3364 3844 3249]
 [7744 7056 7396 8100 7569]
 [5776 6241 5625 6400 6084]
 [8464 9025 8649 9216 8836]
 [3600 4225 3969 4489 3844]
 [6724 6400 7225 6889 6561]
 [4900 5184 4624 5476 4761]]
Square Root:
 [[8.83176087 9.21954446 9.48683298 9.38083152 8.71779789]
 [8.06225775 8.36660027 8.48528137 8.24621125 8.1240384 ]
 [9.48683298 9.59166305 9.69535971 9.43398113 9.53939201]
 [7.41619849 7.74596669 7.61577311 7.87400787 7.54983444]
 [9.38083152 9.16515139 9.2736185  9.48683298 9.32737905]
 [8.71779789 8.88819442 8.66025404 8.94427191 8.83176087]
 [9.59166305 9.74679434 9.64365076 9.79795897 9.69535971]
 [7.74596669 8.06225775 7.93725393 8.18535277 7.87400787]
 [9.05538514 8.94427191 9.21954446 9.11043358 9.        ]
 [8.36660027 8.48528137 8.24621125 8.60232527 8.30662386]]

In [ ]:
# Addition
result_add = data + data
print(result_add)

# Multiplication
result_mul = np.dot(data, data.T)
print(result_mul)

[[156 170 180 176 152]
 [130 140 144 136 132]
 [180 184 188 178 182]
 [110 120 116 124 114]
 [176 168 172 180 174]
 [152 158 150 160 156]
 [184 190 186 192 188]
 [120 130 126 134 124]
 [164 160 170 166 162]
 [140 144 136 148 138]]
[[34929 28500 38048 24398 36276 32361 39213 26483 34306 29456]
 [28500 23289 31116 19929 29654 26458 32058 21634 28040 24072]
 [38048 31116 41602 26627 39659 35376 42860 28907 37488 32181]
 [24398 19929 26627 17082 25407 22676 27464 18542 24003 20635]
 [36276 29654 39659 25407 37865 33760 40892 27582 35763 30719]
 [32361 26458 35376 22676 33760 30126 36484 24616 31885 27410]
 [39213 32058 42860 27464 40892 36484 44190 29814 38631 33194]
 [26483 21634 28907 18542 27582 24616 29814 20127 26058 22400]
 [34306 28040 37488 24003 35763 31885 38631 26058 33799 29011]
 [29456 24072 32181 20635 30719 27410 33194 22400 29011 24945]]

In [ ]:
flat_data = data.flatten()

In [ ]:
Q1 = np.percentile(flat_data, 25)
Q2 = np.percentile(flat_data, 50)
Q3 = np.percentile(flat_data, 75)

print("Q1:", Q1)
print("Median (Q2):", Q2)
print("Q3:", Q3)

Q1: 68.0
Median (Q2): 78.5
Q3: 88.0

In [ ]:
# indexing
print(data[0, 2])   # First student, 3rd subject

90

In [ ]:
# Slicing
print(data[0:3])        # First 3 students
print(data[:, 1])       # All students, 2nd subject

[[78 85 90 88 76]
 [65 70 72 68 66]
 [90 92 94 89 91]]
[85 70 92 60 84 79 95 65 80 72]

In [ ]:
# Using the cloud Dataset
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv("cloud_outages_dataset.csv")
df.head()

,incident_id,cloud_provider,region,service,service_subtype,start_time,end_time,duration_minutes,severity,status,...,post_mortem_link,is_recurrent_issue,previous_incident_id,external_factors,scheduled_maintenance_conflict,patch_applied,system_load_before_outage,system_load_after_outage,backup_system_triggered,notes
0,aeb380d2-6559-4d99-abfb-17e1c45e831b,AWS,europe-west2,Storage,S3,2025-06-30 10:18:08.524480,2025-06-30 13:15:08.524480,177,Low,Monitoring,...,NaN,No,NaN,NaN,No,No,40,46,Yes,Simulated note
1,ddf7e3a0-f44d-4c94-ae32-189213321e2d,IBM,asia-southeast1,AI/ML,RDS,2025-06-28 10:18:08.524591,2025-06-28 20:52:08.524591,634,Low,Investigating,...,NaN,No,NaN,Weather,Yes,No,45,55,Yes,Simulated note
2,b17b9c80-94a0-4ca5-b52f-f1e7853b1240,AWS,europe-west2,Storage,S3,2025-06-01 10:18:08.524638,2025-06-01 14:36:08.524638,258,High,Resolved,...,NaN,No,NaN,DDoS,No,Yes,61,74,No,Simulated note
3,c856b404-e22e-4f84-8bed-9b1512adc9b5,AWS,asia-southeast1,Compute,Lambda,2025-11-30 10:18:08.524678,2025-11-30 19:21:08.524678,543,Medium,Resolved,...,NaN,Yes,NaN,Weather,No,Yes,48,97,Yes,Simulated note
4,42a85996-663a-4f92-94e1-0f205a06db01,IBM,asia-southeast1,AI/ML,Cloud Functions,2025-02-16 10:18:08.524719,2025-02-16 21:03:08.524719,645,Medium,Monitoring,...,NaN,No,NaN,DDoS,No,No,23,75,Yes,Simulated note

In [ ]:
print("Shape of dataset:", df.shape)  # Check Data
print("\nColumns:\n", df.columns)

Shape of dataset: (50000, 40)

Columns:
 Index(['incident_id', 'cloud_provider', 'region', 'service', 'service_subtype',
       'start_time', 'end_time', 'duration_minutes', 'severity', 'status',
       'root_cause_category', 'root_cause_description',
       'number_of_customers_affected', 'estimated_revenue_loss_usd',
       'sla_violation', 'region_impact_score', 'service_impact_score',
       'ticket_count', 'ticket_response_time_minutes',
       'ticket_resolution_time_minutes', 'monitoring_alerts_triggered',
       'detection_method', 'mitigation_action', 'number_of_engineers_involved',
       'engineer_response_time_minutes', 'communication_channels_used',
       'public_status_page_updated', 'status_page_update_count',
       'user_feedback_score', 'post_mortem_completed', 'post_mortem_link',
       'is_recurrent_issue', 'previous_incident_id', 'external_factors',
       'scheduled_maintenance_conflict', 'patch_applied',
       'system_load_before_outage', 'system_load_after_outage',
       'backup_system_triggered', 'notes'],
      dtype='object')

In [ ]:
numeric_df = df.select_dtypes(include=[np.number])  # Select Only Numeric Columns
numeric_df.head()

,duration_minutes,number_of_customers_affected,estimated_revenue_loss_usd,region_impact_score,service_impact_score,ticket_count,ticket_response_time_minutes,ticket_resolution_time_minutes,monitoring_alerts_triggered,number_of_engineers_involved,engineer_response_time_minutes,status_page_update_count,user_feedback_score,post_mortem_link,previous_incident_id,system_load_before_outage,system_load_after_outage
0,177,45023,882914.30,2,8,68,35,234,16,8,5,1,2,NaN,NaN,40,46
1,634,29036,589281.21,20,42,7,26,309,6,6,53,2,5,NaN,NaN,45,55
2,258,86689,130626.30,3,23,29,12,457,6,6,49,3,1,NaN,NaN,61,74
3,543,94893,472354.34,88,0,59,54,399,12,2,27,5,3,NaN,NaN,48,97
4,645,41905,312065.35,47,54,33,36,110,14,8,21,1,1,NaN,NaN,23,75

In [ ]:
data = numeric_df.to_numpy()
print(data[:5])   # first 5 rows

[[1.7700000e+02 4.5023000e+04 8.8291430e+05 2.0000000e+00 8.0000000e+00
  6.8000000e+01 3.5000000e+01 2.3400000e+02 1.6000000e+01 8.0000000e+00
  5.0000000e+00 1.0000000e+00 2.0000000e+00           nan           nan
  4.0000000e+01 4.6000000e+01]
 [6.3400000e+02 2.9036000e+04 5.8928121e+05 2.0000000e+01 4.2000000e+01
  7.0000000e+00 2.6000000e+01 3.0900000e+02 6.0000000e+00 6.0000000e+00
  5.3000000e+01 2.0000000e+00 5.0000000e+00           nan           nan
  4.5000000e+01 5.5000000e+01]
 [2.5800000e+02 8.6689000e+04 1.3062630e+05 3.0000000e+00 2.3000000e+01
  2.9000000e+01 1.2000000e+01 4.5700000e+02 6.0000000e+00 6.0000000e+00
  4.9000000e+01 3.0000000e+00 1.0000000e+00           nan           nan
  6.1000000e+01 7.4000000e+01]
 [5.4300000e+02 9.4893000e+04 4.7235434e+05 8.8000000e+01 0.0000000e+00
  5.9000000e+01 5.4000000e+01 3.9900000e+02 1.2000000e+01 2.0000000e+00
  2.7000000e+01 5.0000000e+00 3.0000000e+00           nan           nan
  4.8000000e+01 9.7000000e+01]
 [6.4500000e+02 4.1905000e+04 3.1206535e+05 4.7000000e+01 5.4000000e+01
  3.3000000e+01 3.6000000e+01 1.1000000e+02 1.4000000e+01 8.0000000e+00
  2.1000000e+01 1.0000000e+00 1.0000000e+00           nan           nan
  2.3000000e+01 7.5000000e+01]]

In [ ]:
mean_values = np.mean(data, axis=0)
print("Mean:\n", mean_values)

Mean:
 [3.61312020e+02 5.02979515e+04 5.01118383e+05 4.99036200e+01
 4.99741800e+01 5.04392800e+01 3.25547200e+01 2.54586100e+02
 1.05521400e+01 5.49896000e+00 3.25031600e+01 2.50274000e+00
 2.99712000e+00            nan            nan 5.51297800e+01
 5.49009200e+01]

In [ ]:
median_values = np.median(data, axis=0)
print("Median:\n", median_values)

Median:
 [3.6100000e+02 5.0299000e+04 5.0219747e+05 5.0000000e+01 5.0000000e+01
 5.0000000e+01 3.3000000e+01 2.5500000e+02 1.1000000e+01 6.0000000e+00
 3.3000000e+01 3.0000000e+00 3.0000000e+00           nan           nan
 5.5000000e+01 5.5000000e+01]

In [ ]:
std_values = np.std(data, axis=0)
print("Standard Deviation:\n", std_values)

Standard Deviation:
 [2.06387037e+02 2.88485570e+04 2.88265364e+05 2.91691119e+01
 2.91132038e+01 2.89068620e+01 1.61659805e+01 1.30331631e+02
 5.75633924e+00 2.87315835e+00 1.60727381e+01 1.71586494e+00
 1.41520024e+00            nan            nan 2.63564113e+01
 2.62245706e+01]

In [ ]:
print("Minimum values:\n", np.min(data, axis=0))
print("Maximum values:\n", np.max(data, axis=0))

Minimum values:
 [5.00000e+00 1.02000e+02 1.00275e+03 0.00000e+00 0.00000e+00 1.00000e+00
 5.00000e+00 3.00000e+01 1.00000e+00 1.00000e+00 5.00000e+00 0.00000e+00
 1.00000e+00         nan         nan 1.00000e+01 1.00000e+01]
Maximum values:
 [7.2000000e+02 9.9999000e+04 9.9999208e+05 1.0000000e+02 1.0000000e+02
 1.0000000e+02 6.0000000e+01 4.8000000e+02 2.0000000e+01 1.0000000e+01
 6.0000000e+01 5.0000000e+00 5.0000000e+00           nan           nan
 1.0000000e+02 1.0000000e+02]

In [ ]:
print("Sum of each column:\n", np.sum(data, axis=0))

Sum of each column:
 [1.80656010e+07 2.51489758e+09 2.50559192e+10 2.49518100e+06
 2.49870900e+06 2.52196400e+06 1.62773600e+06 1.27293050e+07
 5.27607000e+05 2.74948000e+05 1.62515800e+06 1.25137000e+05
 1.49856000e+05            nan            nan 2.75648900e+06
 2.74504600e+06]

In [ ]:
transpose_data = data.T
print("Transpose (first 5 values):\n", transpose_data[:, :5])

Transpose (first 5 values):
 [[1.7700000e+02 6.3400000e+02 2.5800000e+02 5.4300000e+02 6.4500000e+02]
 [4.5023000e+04 2.9036000e+04 8.6689000e+04 9.4893000e+04 4.1905000e+04]
 [8.8291430e+05 5.8928121e+05 1.3062630e+05 4.7235434e+05 3.1206535e+05]
 [2.0000000e+00 2.0000000e+01 3.0000000e+00 8.8000000e+01 4.7000000e+01]
 [8.0000000e+00 4.2000000e+01 2.3000000e+01 0.0000000e+00 5.4000000e+01]
 [6.8000000e+01 7.0000000e+00 2.9000000e+01 5.9000000e+01 3.3000000e+01]
 [3.5000000e+01 2.6000000e+01 1.2000000e+01 5.4000000e+01 3.6000000e+01]
 [2.3400000e+02 3.0900000e+02 4.5700000e+02 3.9900000e+02 1.1000000e+02]
 [1.6000000e+01 6.0000000e+00 6.0000000e+00 1.2000000e+01 1.4000000e+01]
 [8.0000000e+00 6.0000000e+00 6.0000000e+00 2.0000000e+00 8.0000000e+00]
 [5.0000000e+00 5.3000000e+01 4.9000000e+01 2.7000000e+01 2.1000000e+01]
 [1.0000000e+00 2.0000000e+00 3.0000000e+00 5.0000000e+00 1.0000000e+00]
 [2.0000000e+00 5.0000000e+00 1.0000000e+00 3.0000000e+00 1.0000000e+00]
 [          nan           nan           nan           nan           nan]
 [          nan           nan           nan           nan           nan]
 [4.0000000e+01 4.5000000e+01 6.1000000e+01 4.8000000e+01 2.3000000e+01]
 [4.6000000e+01 5.5000000e+01 7.4000000e+01 9.7000000e+01 7.5000000e+01]]

In [ ]:
correlation = np.corrcoef(data, rowvar=False)
print("Correlation Matrix:\n", correlation)

Correlation Matrix:
 [[ 1.00000000e+00 -4.91755354e-03  6.46327427e-04  3.98040342e-03
   1.19904107e-02  3.77042403e-03 -5.80487961e-03  1.41375834e-03
  -9.33019517e-04 -2.07932816e-03 -3.00247847e-03  8.53621884e-04
  -1.90825569e-03             nan             nan -2.96700304e-03
  -7.17113353e-03]
 [-4.91755354e-03  1.00000000e+00 -4.39766901e-03  1.54107073e-04
   6.50769294e-03 -4.26487171e-03 -2.78746014e-03 -4.62121394e-03
  -3.70990981e-03 -1.25083596e-03 -1.84771023e-03  3.15806635e-03
  -2.12096879e-03             nan             nan -6.65643437e-03
   5.81054541e-04]
 [ 6.46327427e-04 -4.39766901e-03  1.00000000e+00  2.48535076e-03
   1.71026793e-03 -4.30649412e-03  8.41758850e-04  3.48394852e-03
   4.96641711e-03 -1.29106134e-03  1.75942559e-03  7.15824921e-04
   9.77041886e-03             nan             nan -5.50736592e-03
   3.01908391e-03]
 [ 3.98040342e-03  1.54107073e-04  2.48535076e-03  1.00000000e+00
  -6.34360406e-03  5.76158664e-03 -2.65618338e-03  6.12889658e-03
   3.61387051e-03  6.07141247e-03  2.80767355e-03  2.50736140e-03
   3.23357539e-03             nan             nan -3.65350803e-03
   4.31191807e-03]
 [ 1.19904107e-02  6.50769294e-03  1.71026793e-03 -6.34360406e-03
   1.00000000e+00 -5.14271038e-03 -4.41254835e-03 -7.26497342e-03
   7.52071462e-04  2.65261826e-03 -4.21117057e-03  6.53838767e-03
  -2.45174462e-03             nan             nan  1.27016582e-02
   4.11449748e-03]
 [ 3.77042403e-03 -4.26487171e-03 -4.30649412e-03  5.76158664e-03
  -5.14271038e-03  1.00000000e+00 -5.27048247e-03 -4.42918044e-03
   2.06839357e-03  1.74788121e-04 -1.42206298e-03 -1.65570924e-03
   4.29160173e-03             nan             nan -2.97052863e-03
   4.47415630e-03]
 [-5.80487961e-03 -2.78746014e-03  8.41758850e-04 -2.65618338e-03
  -4.41254835e-03 -5.27048247e-03  1.00000000e+00 -3.41130082e-03
   2.74216084e-03  4.76101578e-03  1.50461733e-03 -1.25456525e-03
  -2.78180478e-03             nan             nan  6.24334802e-03
  -7.95427777e-04]
 [ 1.41375834e-03 -4.62121394e-03  3.48394852e-03  6.12889658e-03
  -7.26497342e-03 -4.42918044e-03 -3.41130082e-03  1.00000000e+00
   8.61968220e-03 -6.27773065e-03  3.95874196e-03  8.31117734e-04
  -5.21006361e-03             nan             nan -3.55954014e-03
  -2.49730874e-03]
 [-9.33019517e-04 -3.70990981e-03  4.96641711e-03  3.61387051e-03
   7.52071462e-04  2.06839357e-03  2.74216084e-03  8.61968220e-03
   1.00000000e+00 -6.18879940e-03 -1.22454172e-03  5.12469580e-03
   4.17979445e-03             nan             nan  4.19165683e-03
  -4.62099501e-03]
 [-2.07932816e-03 -1.25083596e-03 -1.29106134e-03  6.07141247e-03
   2.65261826e-03  1.74788121e-04  4.76101578e-03 -6.27773065e-03
  -6.18879940e-03  1.00000000e+00  1.66401218e-03 -5.50251851e-03
  -8.95281610e-03             nan             nan -6.78992758e-03
   2.11177924e-03]
 [-3.00247847e-03 -1.84771023e-03  1.75942559e-03  2.80767355e-03
  -4.21117057e-03 -1.42206298e-03  1.50461733e-03  3.95874196e-03
  -1.22454172e-03  1.66401218e-03  1.00000000e+00  5.34186240e-03
   4.30003020e-03             nan             nan -2.23653459e-03
   5.80618144e-05]
 [ 8.53621884e-04  3.15806635e-03  7.15824921e-04  2.50736140e-03
   6.53838767e-03 -1.65570924e-03 -1.25456525e-03  8.31117734e-04
   5.12469580e-03 -5.50251851e-03  5.34186240e-03  1.00000000e+00
   3.90722754e-03             nan             nan -2.95740033e-03
  -2.18518404e-03]
 [-1.90825569e-03 -2.12096879e-03  9.77041886e-03  3.23357539e-03
  -2.45174462e-03  4.29160173e-03 -2.78180478e-03 -5.21006361e-03
   4.17979445e-03 -8.95281610e-03  4.30003020e-03  3.90722754e-03
   1.00000000e+00             nan             nan -6.37717930e-03
   1.04962224e-03]
 [            nan             nan             nan             nan
              nan             nan             nan             nan
              nan             nan             nan             nan
              nan             nan             nan             nan
              nan]
 [            nan             nan             nan             nan
              nan             nan             nan             nan
              nan             nan             nan             nan
              nan             nan             nan             nan
              nan]
 [-2.96700304e-03 -6.65643437e-03 -5.50736592e-03 -3.65350803e-03
   1.27016582e-02 -2.97052863e-03  6.24334802e-03 -3.55954014e-03
   4.19165683e-03 -6.78992758e-03 -2.23653459e-03 -2.95740033e-03
  -6.37717930e-03             nan             nan  1.00000000e+00
   2.61330485e-03]
 [-7.17113353e-03  5.81054541e-04  3.01908391e-03  4.31191807e-03
   4.11449748e-03  4.47415630e-03 -7.95427777e-04 -2.49730874e-03
  -4.62099501e-03  2.11177924e-03  5.80618144e-05 -2.18518404e-03
   1.04962224e-03             nan             nan  2.61330485e-03
   1.00000000e+00]]